### ISSUE TITLE
Execution rerun is failed

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1012]
Failed with following error:
```
2022-08-08 11:54:20	
08:54:20.386 [boundedElastic-6] ERROR c.s.s.o.controller.AgentsController - Unable to create docker containers for executionId=187, will mark it as ERROR
com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"Conflict. The container name \"/save-execution-187-1\" is already in use by container \"f055da3a0583ede91b2411a86b4ff5877cce832d5ddc6d589b85b07313781639\". You have to remove (or rename) that container to be able to reuse that name."}
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:245)
	at com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:37)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:608)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:33)
	at com.saveourtool.save.orchestrator.UtilsKt$execTimed$result$1.get(Utils.kt:71)
	at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:158)
	at com.saveourtool.save.orchestrator.docker.DockerAgentRunner.createContainerFromImage(DockerAgentRunner.kt:278)
	at com.saveourtool.save.orchestrator.docker.DockerAgentRunner.create(DockerAgentRunner.kt:58)
	at com.saveourtool.save.orchestrator.service.DockerService.createContainers(DockerService.kt:95)
	at com.saveourtool.save.orchestrator.controller.AgentsController.initialize$lambda-14$lambda-8(AgentsController.kt:109)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-08 11:54:20	
08:54:20.202 [boundedElastic-6] INFO c.s.s.o.docker.DockerAgentRunner - Building container #1 for execution.id=187
2022-08-08 11:54:20	
08:54:20.202 [boundedElastic-4] INFO c.s.s.o.service.DockerService - For execution.id=187 using base image [id=sha256:c053bb316494bfcf66e218e88cec8b642a7f6f6a0c001316caa756c0014a4621] and PV [id=DockerPvId(volumeName=save-execution-vol-b93b3658-f973-4801-8c08-de743c5ed5ef)]
2022-08-08 11:54:20	
08:54:20.041 [boundedElastic-4] INFO c.s.s.o.service.DockerService - Built persistent volume with tests by id DockerPvId(volumeName=save-execution-vol-b93b3658-f973-4801-8c08-de743c5ed5ef)
2022-08-08 11:54:20	
08:54:20.034 [parallel-2] DEBUG c.g.d.c.exec.InspectContainerCmdExec - GET: DefaultWebTarget{path=[/containers/818d79f48e2b0a144293aac258225543d0722d9fd7aca0a430953f96531884f9/json], queryParams={}}
2022-08-08 11:54:09	
08:54:09.721 [boundedElastic-4] INFO c.s.s.o.d.DockerPersistentVolumeService - Starting container 818d79f48e2b0a144293aac258225543d0722d9fd7aca0a430953f96531884f9 to copy files from [/tmp/save-execution-18711041578986244691411] into volume save-execution-vol-b93b3658-f973-4801-8c08-de743c5ed5ef
2022-08-08 11:54:09	
08:54:09.665 [docker-java-stream-112319417] DEBUG c.g.d.a.c.PullImageResultCallback - ResponseItem(stream=null, status=Status: Image is up to date for alpine:latest, progressDetail=null, progress=null, id=null, from=null, time=null, errorDetail=null, error=null, aux=null)
2022-08-08 11:54:09	
08:54:09.664 [docker-java-stream-112319417] DEBUG c.g.d.a.c.PullImageResultCallback - ResponseItem(stream=null, status=Digest: sha256:7580ece7963bfa863801466c0a488f11c86f85d9988051a9f9c68cb27f6b7872, progressDetail=null, progress=null, id=null, from=null, time=null, errorDetail=null, error=null, aux=null)
2022-08-08 11:54:09	
08:54:09.652 [docker-java-stream-112319417] DEBUG c.g.d.a.c.PullImageResultCallback - ResponseItem(stream=null, status=Pulling from library/alpine, progressDetail=null, progress=null, id=latest, from=null, time=null, errorDetail=null, error=null, aux=null)
2022-08-08 11:54:06	
08:54:06.739 [boundedElastic-4] INFO c.s.s.o.service.DockerService - Preparing image and volume for execution.id=187
2022-08-08 11:54:06	
08:54:06.738 [reactor-http-epoll-1] WARN c.s.s.o.controller.AgentsController - Not found any additional files for execution 187
2022-08-08 11:54:06	
08:54:06.738 [reactor-http-epoll-1] INFO c.s.s.o.controller.AgentsController - Downloaded all tests for execution 187 to /tmp/save-execution-18711041578986244691411/test-suites
2022-08-08 11:54:06	
08:54:06.688 [boundedElastic-4] WARN c.s.s.o.controller.AgentsController - Not found any tests for execution 187
2022-08-08 11:54:06	
08:54:06.686 [boundedElastic-4] INFO c.s.s.o.controller.AgentsController - Starting preparations for launching execution [project=Project(name=Diktat, url=https://github.com/diktat-static-analysis/diKTat, description=Save DEMO examples are run with Diktat static analyzer for Kotlin, status=CREATED, public=true, userId=null, email=, numberOfContainers=3, organization=Organization(name=CQFN.org, status=CREATED, ownerId=3, dateCreated=2022-03-25T12:45:38, avatar=/CQFN.org/logo-1024.png, description=Code Quality Foundation.
Focus on Kotlin and Static Analysis 
, canCreateContests=true), contestRating=0), id=187, status=PENDING]
2022-08-08 11:54:05	
08:54:05.761 [reactor-http-epoll-4] INFO c.s.s.o.service.DockerService - Image save-execution:187 is not present, so won't attempt to remove
2022-08-08 11:54:05	
08:54:05.609 [reactor-http-epoll-4] INFO c.s.s.o.service.DockerService - Removing image save-execution:187
```

**Comment by nulls** [comment]
Need to change logic about reusing execution id. 
We can create a new execution id on re-run (proper full run with the same resources)

**Comment by kgevorkyan** [comment]
Sometimes I met such exceptions even in simple run, however in my stand I quite roughly remove and stop all components, so I didn 't attach much importance to this

Probably we can additionally check, whether current container id already exist, before creating it

**Comment by nulls** [comment]
Changing logic for rerun in scope of #1028 by creating a new execution for re-run
