### ISSUE TITLE
Infinite recursion when trying to serialize `Execution`

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1130]
```
ERROR c.s.s.b.c.RunExecutionController - Error during preprocessing. Reason: JSON encoding error: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: com.saveourtool.save.entities.User["originalLogins"]->org.hibernate.collection.internal.PersistentBag[0]->com.saveourtool.save.entities.OriginalLogin["user"]->com.saveourtool.save.entities.User["originalLogins"]->org.hibernate.collection.internal.PersistentBag[0]->com.saveourtool.save.entities.OriginalLogin["user"]->com.saveourtool.save.entities.User["originalLogins"]->org.hibernate.collection.internal.PersistentBag[0]->com.saveourtool.save.entities.OriginalLogin["user"]->com.saveourtool.save.entities.User["originalLogins"]->org.hibernate.collection.internal.PersistentBag[0]->com.saveourtool.save.entities.OriginalLogin["user"]->com.saveourtool.save.entities.User["originalLogins"]->org.hibernate.collection.internal.PersistentBag[0]->com.saveourtool.save.entities.OriginalLogin["user"]->com.saveourtool.save.entities.User["originalLogins"]...
at org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:233)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Request to POST http://orchestrator:5100/initializeAgents [DefaultWebClient]
Original Stack Trace:
		at org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:233)
		at org.springframework.http.codec.json.AbstractJackson2Encoder.lambda$encode$0(AbstractJackson2Encoder.java:150)
```

Occurs after #965, where `User.originalLogin` has been introduced.

**Comment by petertrr** [comment]
@Cheshiriks take a look at https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion and also please add a test that would serialize and deserialize `User` with circular references.
