### ISSUE TITLE
Processing with default SDK does not work 

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1302]
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/58667063/194718784-d19ae27e-f4c7-4cf9-ae77-65582808a525.png">

Default SDK processing does not work. We also need to remember what the default SDK is. 
@petertrr may be you remember, what is it for?

**Comment by petertrr** [comment]
How exactly does it not work?
The default SDK is actually a system without any particular SDK for tools that don't need a runtime, e.g. compiled C++ tools. We simply map it to Ubuntu:latest.

**Comment by akuleshov7** [comment]
Ah, may be we should rename it to "NO SDK"

**Comment by akuleshov7** [comment]
It fallbacks to Java:

```
20:02:34.177 [boundedElastic-6] ERROR c.s.s.o.controller.AgentsController - Unable to create containers for executionId=1, will mark it as ERROR com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"manifest unknown"}
```

**Comment by nulls** [comment]
> How exactly does it not work? The default SDK is actually a system without any particular SDK for tools that don't need a runtime, e.g. compiled C++ tools. We simply map it to Ubuntu:latest.

It tries to run `ghcr.io/saveourtool/save-base:ubuntu-latest` which doesn't exist here https://github.com/saveourtool/save-cloud/pkgs/container/save-base/versions?filters%5Bversion_type%5D=tagged
Logs:
```
12:05:53.420 [boundedElastic-5] INFO c.s.s.o.service.DockerService - For execution.id=39 using base image [ghcr.io/saveourtool/save-base:ubuntu-latest] 
12:05:53.420 [boundedElastic-6] DEBUG o.s.w.s.a.HttpWebHandlerAdapter - [cff06856-25] Completed 202 ACCEPTED 
12:05:54.593 [docker-java-stream-542118296] ERROR c.g.d.a.async.ResultCallbackTemplate - Error during callback com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"manifest unknown"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)

12:05:54.593 [boundedElastic-7] ERROR c.s.s.o.controller.AgentsController - Unable to create containers for executionId=39, will mark it as ERROR com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"manifest unknown"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
