### ISSUE TITLE
TestSuitesSourceFetcher issue

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1619]
Usecase (https://saveourtool.com/#/organization/CQFN.org/tests)
1. Fetch a new snapshot from branch `main` in `SaveCliTest-kotlin-diktat` from the main page
2. Fetch a new snapshot from branch `save-integration-test` in `kotlin-diktat` from the main page (branch should be a single in `seletlist`)
3. Check logs for `preprocessor` in `grafana`: there should be error like:
```
14:53:47.401 [boundedElastic-1] INFO c.s.s.p.c.GitPreprocessorController - Received a request to detect a list of branches in https://github.com/0x6675636b796f75676974687562/save-kotlin-diktat 
14:53:51.803 [reactor-http-epoll-2] ERROR c.s.s.p.s.GitPreprocessorService - Failed to clone git repository https://github.com/0x6675636b796f75676974687562/save-kotlin-diktat java.lang.IllegalStateException: Error in JGit API
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.withRethrow(GitUtil.kt:163)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.gitCallWithRethrow(GitUtil.kt:151)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.callWithRethrow(GitUtil.kt:155)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.doCloneToDirectory(GitUtil.kt:126)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.doCloneToDirectory$default(GitUtil.kt:108)
Caused by: org.eclipse.jgit.api.errors.TransportException: Remote branch 'main' not found in upstream origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:246)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:1)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt$callWithRethrow$1.invoke(GitUtil.kt:156)
Caused by: org.eclipse.jgit.errors.TransportException: Remote branch 'main' not found in upstream origin
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:155)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325)
14:53:51.804 [reactor-http-epoll-2] INFO c.s.s.p.s.GitPreprocessorService - Start cleanup of /home/cnb/repositories/tmp/repository-11694836410553457471 
14:53:51.804 [reactor-http-epoll-2] ERROR c.s.s.p.c.TestSuitesPreprocessorController - Failed to fetch from main java.lang.IllegalStateException: Error in JGit API
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.withRethrow(GitUtil.kt:163)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.gitCallWithRethrow(GitUtil.kt:151)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.callWithRethrow(GitUtil.kt:155)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.doCloneToDirectory(GitUtil.kt:126)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.doCloneToDirectory$default(GitUtil.kt:108)
Caused by: org.eclipse.jgit.api.errors.TransportException: Remote branch 'main' not found in upstream origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:246)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:1)
	at com.saveourtool.save.preprocessor.utils.GitUtilKt$callWithRethrow$1.invoke(GitUtil.kt:156)
Caused by: org.eclipse.jgit.errors.TransportException: Remote branch 'main' not found in upstream origin
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:155)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325)
```

Frontend sends a request to preprocessor with branch name selected in step **1**

It also can be checked in browser by `Inspect/Network`
![image](https://user-images.githubusercontent.com/1164369/207631547-6ad8fe70-7785-4f60-9fe5-640638babbf1.png)

**Comment by Arrgentum** [comment]
```kotlin

  | 2022-12-16 17:30:10 | 14:30:10.654 [reactor-http-epoll-2] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError: 500 Internal Server Error from POST http://preprocessor/test-suites-sources/fetch?mode=BY_BRANCH&version=main Caused by: org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError: 500 Internal Server Error from POST http://preprocessor/test-suites-sources/fetch?mode=BY_BRANCH&version=main 	at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:239) 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:  Error has been observed at the following site(s): 	*__checkpoint ? 500 from POST http://preprocessor/test-suites-sources/fetch [DefaultWebClient] Original Stack Trace: 		at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:239) 		at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:207) 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) 		at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162) 		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:101) 



  | 2022-12-16 17:30:10 | 14:30:10.650 [boundedElastic-113] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [66f5f6d9-28680]  500 Server Error for HTTP DELETE "/internal/test-suites-sources/CQFN.org/SaveCliTest-kotlin-diktat/delete-test-suites-and-snapshot?version=main" java.lang.IllegalArgumentException: Expected that we remove all test suites related to a single execution at once 	at com.saveourtool.save.backend.service.TestSuitesService.doDeleteTestSuite(TestSuitesService.kt:188) 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:  Error has been observed at the following site(s): 	*__checkpoint ? Handler com.saveourtool.save.backend.controllers.TestSuitesSourceController#deleteTestSuitesAndSnapshot(String, String, String) [DispatcherHandler] 	*__checkpoint ? com.saveourtool.save.backend.configs.UserLoggingFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain] 	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] 	*__checkpoint ? HTTP DELETE "/internal/test-suites-sources/CQFN.org/SaveCliTest-kotlin-diktat/delete-test-suites-and-snapshot?version=main" [ExceptionHandlingWebHandler] Original Stack Trace: 		at com.saveourtool.save.backend.service.TestSuitesService.doDeleteTestSuite(TestSuitesService.kt:188) 		at com.saveourtool.save.backend.service.TestSuitesService.deleteTestSuite(TestSuitesService.kt:178) 		at com.saveourtool.save.backend.service.TestSuitesService$FastClassBySpringCGLIB$fb546ab8.invoke(<generated>) 		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) 		at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)


````

**Comment by nulls** [comment]
@Arrgentum did you fix it?
