### ISSUE TITLE
IAE: "Expected that we remove all test suites related to a single execution at once" when deleting a fetched test suite source

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#1743]
Back-end version is `0.4.0-alpha.0.1-08a9fa4` (commit 08a9fa409793b52096d79fccf0cabfb89730445d).

Caused by (presumably) 88ad7a99.

```
2023-01-20 13:32:29	
10:32:29.140 [boundedElastic-2] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [97f90b5b-913]  500 Server Error for HTTP DELETE "/api/v1/test-suites-sources/CQFN.org/kotlin-diktat/delete-test-suites-and-snapshot?version=save-integration-test" java.lang.IllegalArgumentException: Expected that we remove all test suites related to a single execution at once
	at com.saveourtool.save.backend.service.TestSuitesService.doDeleteTestSuite(TestSuitesService.kt:240)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler com.saveourtool.save.backend.controllers.TestSuitesSourceController#deleteTestSuitesAndSnapshot(String, String, String) [DispatcherHandler]
	*__checkpoint ? com.saveourtool.save.backend.configs.UserLoggingFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP DELETE "/api/v1/test-suites-sources/CQFN.org/kotlin-diktat/delete-test-suites-and-snapshot?version=save-integration-test" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at com.saveourtool.save.backend.service.TestSuitesService.doDeleteTestSuite(TestSuitesService.kt:240)
		at com.saveourtool.save.backend.service.TestSuitesService.deleteTestSuite(TestSuitesService.kt:230)
		at com.saveourtool.save.backend.service.TestSuitesService$$FastClassBySpringCGLIB$$fb546ab8.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
```

**Comment by nulls** [comment]
test suites are duplicated 5 times.
looks like we add a new test suite without checking that version existed already

**Comment by nulls** [comment]
It was refactored: now snapshot and version are split to two separate entities. Version is just label.

Closed since there is no such endpoint as `/delete-test-suites-and-snapshot`
