### ISSUE TITLE
ISE: `Symbol for kotlinx.serialization.modules/SerializersModuleCollector.polymorphicDefaultDeserializer|-5554727982800535415[0] is unbound`

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#1924]
When compiling `:save-cloud-common`:

```
> Task :save-cloud-common:compileTestKotlinJsIr
> Task :save-cloud-common:jsIrTestProcessResources NO-SOURCE
> Task :save-cloud-common:jsIrTestClasses
> Task :save-cloud-common:compileTestDevelopmentExecutableKotlinJsIr
```

Exception:

```
java.lang.IllegalStateException: Symbol for kotlinx.serialization.modules/SerializersModuleCollector.polymorphicDefaultDeserializer|-555[472](https://github.com/saveourtool/save-cloud/actions/runs/4313856636/jobs/7526778193#step:8:474)7982800535415[0] is unbound
	at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.getOwner(IrPublicSymbolBase.kt:52)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.collectImplementedSymbol(CacheUpdater.kt:299)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.getExportedSignaturesAndAddMetadata-gNUL48g(CacheUpdater.kt:351)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.rebuildDirtySourceMetadata(CacheUpdater.kt:403)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.actualizeCachesImpl(CacheUpdater.kt:704)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.actualizeCaches(CacheUpdater.kt:738)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:300)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:183)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1645)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

`:compileTestDevelopmentExecutableKotlinJsIr` fails, full log [here](https://github.com/saveourtool/save-cloud/actions/runs/4313856636/jobs/7526778193#step:8:453).

Build scan: https://gradle.com/s/knmw4co23mdl6.

**Comment by 0x6675636b796f75676974687562** [comment]
Both `save-cli` and `sarif-utils` now use the same `kotlinx-serialization` version, which is **1.5.0**.
