### ISSUE TITLE
NPE on file upload to S3-based FileStorage

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1932]
### Steps to reproduce:
 1. Go to [saveourtool](saveourtool.com)
 2. Log in
 3. Go to `ProjectView` (e.g. [diktat project](https://saveourtool.com/#/project/CQFN.org/diktat/run))
 4. Try to upload anything to storage
 5. ...
 6. 500 Server Error for HTTP POST "/api/v1/files/CQFN.org/Ktlint/upload" java.lang.NullPointerException: scheduler

Also, storage seems to be unavailable from `saveourtool`.

### Logs fragment:
```
15:20:14.459 [reactor-http-epoll-4] DEBUG o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [28faf290-435] Resolved [NullPointerException: scheduler] for HTTP POST /api/v1/files/CQFN.org/Ktlint/upload 
15:20:14.459 [reactor-http-epoll-4] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [28faf290-435]  500 Server Error for HTTP POST "/api/v1/files/CQFN.org/Ktlint/upload" java.lang.NullPointerException: scheduler
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler com.saveourtool.save.backend.controllers.FileController#upload(Mono, long, String, String, Authentication) [DispatcherHandler]
	*__checkpoint ? com.saveourtool.save.backend.configs.UserLoggingFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP POST "/api/v1/files/CQFN.org/Ktlint/upload" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.Objects.requireNonNull(Unknown Source)
		at reactor.core.publisher.MonoSubscribeOnCallable.<init>(MonoSubscribeOnCallable.java:42)
		at reactor.core.publisher.Mono.subscribeOn(Mono.java:4589)
		at com.saveourtool.save.storage.DefaultStorageProjectReactor.callAsMono(DefaultStorageProjectReactor.kt:163)
		at com.saveourtool.save.storage.DefaultStorageProjectReactor.findExistedS3Key(DefaultStorageProjectReactor.kt:155)
```

**Comment by sanyavertolet** [comment]
Not so easy

```
15:02:50.405 [reactor-http-epoll-4] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [19ee9bd8-220]  500 Server Error for HTTP POST "/api/v1/files/CQFN.org/Ktlint/upload" java.lang.NullPointerException: Cannot invoke "com.saveourtool.save.utils.BlockingBridge.blockingToMono(kotlin.jvm.functions.Function0)" because the return value of "com.saveourtool.save.storage.key.AbstractS3KeyDatabaseManager.getBlockingBridge()" is null
	at com.saveourtool.save.storage.DefaultStorageProjectReactor.callAsMono(DefaultStorageProjectReactor.kt:161)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler com.saveourtool.save.backend.controllers.FileController#upload(Mono, long, String, String, Authentication) [DispatcherHandler]
	*__checkpoint ? com.saveourtool.save.backend.configs.UserLoggingFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP POST "/api/v1/files/CQFN.org/Ktlint/upload" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at com.saveourtool.save.storage.DefaultStorageProjectReactor.callAsMono(DefaultStorageProjectReactor.kt:161)
		at com.saveourtool.save.storage.DefaultStorageProjectReactor.findExistedS3Key(DefaultStorageProjectReactor.kt:155)
		at com.saveourtool.save.storage.DefaultStorageProjectReactor.doesExist(DefaultStorageProjectReactor.kt:142)
		at com.saveourtool.save.storage.AbstractReactiveStorage$doesExist$1.invoke(AbstractReactiveStorage.kt:60)
		at com.saveourtool.save.storage.AbstractReactiveStorage$doesExist$1.invoke(AbstractReactiveStorage.kt:60)
```

**Comment by nulls** [comment]
cc @akuleshov7 
Two findings (Spring vs Kotlin):
# Spring doesn't consider default values of constructor's arguments in dependency injections, they are `null`. Actually, IDE highlights it as a warning that beans are not defined in context, but it can be hidden by class hierarchy (parent has default arguments in constructor and is not a bean; child doesn't have such arguments in constructor, but is a bean)
# Spring's proxy cannot override a closed property, it silently resolves it to `null`. It's expected that Spring cannot proxy such property, but it was a surprise that Spring handles it without any message in logs
