### ISSUE TITLE
save-preprocessor cannot start

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#2200]
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
14:48:23.663 [main] ERROR o.s.boot.SpringApplication - Application run failed org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'awesomeBenchmarksDownloadController' defined in file [/workspace/BOOT-INF/classes/com/saveourtool/save/preprocessor/controllers/AwesomeBenchmarksDownloadController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitPreprocessorService' defined in file [/workspace/BOOT-INF/classes/com/saveourtool/save/preprocessor/service/GitPreprocessorService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.saveourtool.save.preprocessor.service.GitPreprocessorService]: Constructor threw exception; nested exception is java.nio.file.AccessDeniedException: /home/cnb/repositories
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitPreprocessorService' defined in file [/workspace/BOOT-INF/classes/com/saveourtool/save/preprocessor/service/GitPreprocessorService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.saveourtool.save.preprocessor.service.GitPreprocessorService]: Constructor threw exception; nested exception is java.nio.file.AccessDeniedException: /home/cnb/repositories
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.saveourtool.save.preprocessor.service.GitPreprocessorService]: Constructor threw exception; nested exception is java.nio.file.AccessDeniedException: /home/cnb/repositories
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
Caused by: java.nio.file.AccessDeniedException: /home/cnb/repositories
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
```

According to logs, access to `/home/cnb/repositories` is denied. Might not exist. Creating `/home/cnb/repositories` on each node did't help

**Comment by nulls** [comment]
> Creating `/home/cnb/repositories` on each node did't help

Need to create `/tmp/save/repos`
```yaml
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.preprocessor) | indent 10 | trim }}
        - name: repos-storage
          # This mount is not intended to be shared among nodes, because this is temporary data,
          # and each pod of preprocessor can `git clone` on its own.
          hostPath:
            path: /tmp/save/repos
```

**Comment by sanyavertolet** [comment]
> > Creating `/home/cnb/repositories` on each node did't help
> 
> Need to create `/tmp/save/repos`
> 
> ```yaml
>       volumes:
>         - {{ include "spring-boot.config-volume" (dict "service" .Values.preprocessor) | indent 10 | trim }}
>         - name: repos-storage
>           # This mount is not intended to be shared among nodes, because this is temporary data,
>           # and each pod of preprocessor can `git clone` on its own.
>           hostPath:
>             path: /tmp/save/repos
> ```

Will do it soon

**Comment by akuleshov7** [comment]
> > Creating `/home/cnb/repositories` on each node did't help
> 
> Need to create `/tmp/save/repos`
> 
> ```yaml
>       volumes:
>         - {{ include "spring-boot.config-volume" (dict "service" .Values.preprocessor) | indent 10 | trim }}
>         - name: repos-storage
>           # This mount is not intended to be shared among nodes, because this is temporary data,
>           # and each pod of preprocessor can `git clone` on its own.
>           hostPath:
>             path: /tmp/save/repos
> ```

btw and why does Spring complain about /home/cnb?

**Comment by nulls** [comment]
> > > Creating `/home/cnb/repositories` on each node did't help
> > 
> > 
> > Need to create `/tmp/save/repos`
> > ```yaml
> >       volumes:
> >         - {{ include "spring-boot.config-volume" (dict "service" .Values.preprocessor) | indent 10 | trim }}
> >         - name: repos-storage
> >           # This mount is not intended to be shared among nodes, because this is temporary data,
> >           # and each pod of preprocessor can `git clone` on its own.
> >           hostPath:
> >             path: /tmp/save/repos
> > ```
> 
> btw and why does Spring complain about /home/cnb?

We mount it to container as `/home/cnb`
```yaml
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
            - name: repos-storage
              mountPath: /home/cnb
```

**Comment by sanyavertolet** [comment]
@nulls all three nodes have `/tmp/save/repos` created (there is even `config` folder in it). Preprocessor still fails.

**Comment by sanyavertolet** [comment]
The problem took place because of lack of permissions. `chmod 777 -R /tmp/save` fixed the problem:

```
08:56:30.881 [main] INFO o.s.b.w.e.netty.NettyWebServer - Netty started on port 5200 
08:56:30.951 [main] INFO o.s.b.a.e.web.EndpointLinksResolver - Exposing 14 endpoint(s) beneath base path '/actuator' 
08:56:30.991 [main] INFO o.s.b.w.e.netty.NettyWebServer - Netty started on port 5201 
08:56:31.007 [main] INFO c.s.s.p.SavePreprocessorKt - Started SavePreprocessorKt in 3.707 seconds (JVM running for 4.243) 
```

**Comment by nulls** [comment]
> > The problem took place because of lack of permissions. `chmod 777 -R /tmp/save` fixed the problem:
> > ```
> > 08:56:30.881 [main] INFO o.s.b.w.e.netty.NettyWebServer - Netty started on port 5200 
> > 08:56:30.951 [main] INFO o.s.b.a.e.web.EndpointLinksResolver - Exposing 14 endpoint(s) beneath base path '/actuator' 
> > 08:56:30.991 [main] INFO o.s.b.w.e.netty.NettyWebServer - Netty started on port 5201 
> > 08:56:31.007 [main] INFO c.s.s.p.SavePreprocessorKt - Started SavePreprocessorKt in 3.707 seconds (JVM running for 4.243) 
> > ```
> 
> shouldn't we automate it somehow? if we will redeploy from scratch, think permissions will be lost

It's configuration of nodes (physical machine). Cannot be automated by our kube setup.
But we should avoid using such folders\volumes in future

**Comment by kgevorkyan** [comment]
> > > The problem took place because of lack of permissions. `chmod 777 -R /tmp/save` fixed the problem:
> > > ```
> > > 08:56:30.881 [main] INFO o.s.b.w.e.netty.NettyWebServer - Netty started on port 5200 
> > > 08:56:30.951 [main] INFO o.s.b.a.e.web.EndpointLinksResolver - Exposing 14 endpoint(s) beneath base path '/actuator' 
> > > 08:56:30.991 [main] INFO o.s.b.w.e.netty.NettyWebServer - Netty started on port 5201 
> > > 08:56:31.007 [main] INFO c.s.s.p.SavePreprocessorKt - Started SavePreprocessorKt in 3.707 seconds (JVM running for 4.243) 
> > > ```
> > 
> > 
> > shouldn't we automate it somehow? if we will redeploy from scratch, think permissions will be lost
> 
> It's configuration of nodes (physical machine). Cannot be automated by our kube setup. But we should avoid using such folders\volumes in future

we cant add command with `chmod` in some of our script?
