### ISSUE TITLE
HTTP 500 when attempting to read or update the user profile picture

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#2967]
**0.2.1+1056**, Docker tag **0.4.0-alpha.0.379-70423bd**, commit 70423bddd69f7724102894923e9cc6aa32433737:

 - `POST https://cosv.gitlink.org.cn/api/v1/avatar/upload?owner=0x6675636b796f75676974&type=USER`
 - `GET https://cosv.gitlink.org.cn/api/v1/avatar/users/0x6675636b796f75676974?1`

Backend log messages:

```bash
kubectl logs backend-d44fb4fbf-bxdmv --container=backend --follow=true
```

**Comment by 0x6675636b796f75676974687562** [comment]
Backend log fragment:

```console
16:06:34.360 [s3-operations-save-obs-0] DEBUG o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [59e76884-4555] Resolved [S3Exception: null (Service: S3, Status Code: 403, Request ID: 00000192DE2DC46E414869A4463726B1, Extended Request ID: MOCKQjIxQTYxQzZDMDAwMDAxMzQwMzFCRTgwMDUyOTNBQUFBQUFBQWJiYmJiYmJi)] for HTTP GET /api/v1/avatar/organizations/OSV 
16:06:34.360 [s3-operations-save-obs-0] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [59e76884-4555]  500 Server Error for HTTP GET "/api/v1/avatar/organizations/OSV?1" software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 403, Request ID: 00000192DE2DC46E414869A4463726B1, Extended Request ID: MOCKQjIxQTYxQzZDMDAwMDAxMzQwMzFCRTgwMDUyOTNBQUFBQUFBQWJiYmJiYmJi)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler com.saveourtool.save.backend.controllers.AvatarController#getImage(String, String) [DispatcherHandler]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? com.saveourtool.save.backend.configs.UserLoggingFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP GET "/api/v1/avatar/organizations/OSV?1" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
		at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:279)

16:06:34.361 [s3-operations-save-obs-0] DEBUG o.s.h.codec.json.Jackson2JsonEncoder - [59e76884-4555] Encoding [{timestamp=Wed Oct 30 16:06:34 UTC 2024, path=/api/v1/avatar/organizations/OSV, status=500, error=In (truncated)...] 
16:06:34.361 [reactor-http-epoll-4] DEBUG o.s.w.s.a.HttpWebHandlerAdapter - [59e76884-4555] Completed 500 INTERNAL_SERVER_ERROR 
16:06:41.884 [reactor-http-epoll-4] DEBUG o.s.w.s.a.HttpWebHandlerAdapter - [7961574f-4556] HTTP HEAD "/api/v1/avatar/upload?owner=0x6675636b796f75676974&type=USER" 
```

**Comment by 0x6675636b796f75676974687562** [comment]
Backend log fragment:

```console
16:06:41.941 [s3-operations-save-obs-2] DEBUG o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [59e76884-4557] Resolved [S3Exception: null (Service: S3, Status Code: 403, Request ID: 00000192DE2DE20141698F791A967C41, Extended Request ID: MOCKQjIxQTYxQzZDMDAwMDAxMzQwMzFCRTgwMDUyOTNBQUFBQUFBQWJiYmJiYmJi)] for HTTP HEAD /api/v1/avatar/users/0x6675636b796f75676974 
16:06:41.941 [s3-operations-save-obs-2] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [59e76884-4557]  500 Server Error for HTTP HEAD "/api/v1/avatar/users/0x6675636b796f75676974?1" software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 403, Request ID: 00000192DE2DE20141698F791A967C41, Extended Request ID: MOCKQjIxQTYxQzZDMDAwMDAxMzQwMzFCRTgwMDUyOTNBQUFBQUFBQWJiYmJiYmJi)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler com.saveourtool.save.backend.controllers.AvatarController#getImage(String, String) [DispatcherHandler]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? com.saveourtool.save.backend.configs.UserLoggingFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP HEAD "/api/v1/avatar/users/0x6675636b796f75676974?1" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
		at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:279)
```

**Comment by 0x6675636b796f75676974687562** [comment]
Resolved by re-enabling the OBS user.

**Comment by 0x6675636b796f75676974687562** [comment]
Verified as working for:

 - Helm chart **`0.2.1+1179`**
 - Docker tag **`0.4.0-alpha.0.413-620a3ea`**
 - Commit 620a3ea
